version: '3.8'
services:
  database:
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: dummy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  api:
    build: .
    restart: unless-stopped
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: database
      PGPORT: 5432
      PGDATABASE: dummy
      WAIT_HOSTS: database:5432
      JWT_REFRESH_SECRET: 'secret3hbckzjxczc6789'
      JWT_ACCESS_SECRET: 'secret267890sadfhbasdskdas%^&*()'
      HASH_SECRET: 'secret3asdjasbdvjhsa'
    command: ["bash", "-c", "/wait && bash run.sh"]
    volumes:
      - ./core:/url_shortner-api/core:ro
    ports:
      - "8421:8421"
