"""Initial migration.

Revision ID: 4078b3b57e24
Revises: 
Create Date: 2021-09-16 08:05:36.381863

"""
from alembic import op
import sqlalchemy as sa

from core import db
from core.models.users import User

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute("""
        create table users (
            id varchar(255) primary key not null,
            email varchar(255) not null,
            password varchar(255) not null,
            full_name varchar(255) not null,
            mobile varchar(255) not null,
            created_at timestamp with time zone not null,
            updated_at timestamp with time zone not null
        );        
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
